[package]
name = "sysy-analyzer"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "syan"
path = "src/main.rs"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
lalrpop-util = { version = "0.19.7", features = ["lexer"] }
regex = "1"
rlua = "0.19.1"
